server:
  port: 8080

spring:
  application:
    name: noi_that_api

  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/noithat_db?useSSL=true&requireSSL=true&sslMode=REQUIRED&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&connectTimeout=30000
    username: 31J24g8N3fVgA4Z.root
    password: 4R9YX1CuYLRycsse
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      connection-timeout: 20000
      validation-timeout: 3000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false                    # ← Tắt khi deploy
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    lazy-initialization: true          # ← Rất quan trọng

  # Tối ưu cho Render Free
  mvc:
    async:
      request-timeout: 30000

vnpay:
  tmnCode: 9MU9VSCU
  secretKey: QV3VBGE23A4CW825WVEH5QWV4NVV0WEA
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://noi-that-api.onrender.com/api/internal/payments/vnpay/callback