server:
  port: 8080

spring:
  application:
    name: noi_that_api

  datasource:
    url: jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/noithat_db?useSSL=true&requireSSL=true&sslMode=REQUIRED&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&connectTimeout=30000
    username: 31J24g8N3fVgA4Z.root
    password: 4R9YX1CuYLRycsse
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # ← giữ nguyên tên bảng UPPERCASE

  flyway:
    enabled: false

  jwt:
    signerKey: "4f884fa882b67ebc440665bed54fa5e8eebe1f7964f54e63b7607eeb54b0d46a"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ngobao6204@gmail.com
    password: juvo xasw vvjg qwxt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

vnpay:
  tmnCode: 9MU9VSCU
  secretKey: QV3VBGE23A4CW825WVEH5QWV4NVV0WEA
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/internal/payments/vnpay/callback